name: Stake
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch: {}
  push:
    paths:
      - "**.py"
jobs:
  stake:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.5"
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.2
        with:
          poetry-version: "1.1.6"
      - name: Set up Poetry virtualenv
        run: poetry env use python3.9
      - name: Install dependency libraries
        run: poetry install
      - name: Stake
        env:
          FTX_API_KEY: ${{ secrets.FTX_API_KEY }}
          FTX_API_SECRET: ${{ secrets.FTX_API_SECRET }}
          FTX_STAKE_SYMBOLS: ${{ secrets.FTX_STAKE_SYMBOLS }}
        run: poetry run python ./src/app.py
